In [1]:
import numpy as np

basic

In [2]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [3]:
d = np.array([1,2,3],dtype='int32')
print(d)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,3.0],[3.1,2.3,1.2],[1.0,2.0,3.0],[3.1,2.3,1.2]])
print(b)

[[1.  2.  3. ]
 [3.1 2.3 1.2]
 [1.  2.  3. ]
 [3.1 2.3 1.2]]


In [5]:
c = np.array([[[1.0,2.0,3.0],[3.1,2.3,1.2]],[[1.0,2.0,3.0],[3.1,2.3,1.2]]])
print(c)

[[[1.  2.  3. ]
  [3.1 2.3 1.2]]

 [[1.  2.  3. ]
  [3.1 2.3 1.2]]]


In [6]:
a.ndim,b.ndim,c.ndim

(1, 2, 3)

In [7]:
a.shape

(3,)

In [8]:
b.shape

(4, 3)

In [9]:
c.shape

(2, 2, 3)

In [10]:
a.dtype

dtype('int16')

In [11]:
b.dtype

dtype('float64')

In [12]:
a.itemsize#returns the byte memory

2

In [13]:
d.itemsize

4

In [14]:
a.size #returns the size of the matrix

3

In [15]:
total = a.size * a.itemsize
total

6

In [16]:
#or
a.nbytes

6

In [17]:
b.nbytes

96

accessing,changing,rows,colums

In [18]:
e = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
e.shape,e

((2, 7),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]))

In [19]:
e[1,5]

13

In [20]:
e[1,-5]


10

In [21]:
e[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
e[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
e[0,1:6:2]
# 0 means the row here first row 1 means starting index 6 means ening index,2 means step

array([2, 4, 6])

In [24]:
e[:,2]

array([ 3, 10])

In [25]:
b,b.shape

(array([[1. , 2. , 3. ],
        [3.1, 2.3, 1.2],
        [1. , 2. , 3. ],
        [3.1, 2.3, 1.2]]),
 (4, 3))

In [26]:
b[0,1:3]

array([2., 3.])

In [27]:
e[0,1:-1:2]

array([2, 4, 6])

In [28]:
e

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [29]:
e[1,5] = 15
e

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 15, 14]])

In [30]:
e[:,5] = 20
e

array([[ 1,  2,  3,  4,  5, 20,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [31]:
e[:,1],e[:,2] = 100,99
e

array([[  1, 100,  99,   4,   5,  20,   7],
       [  8, 100,  99,  11,  12,  20,  14]])

In [32]:
e[:,:] = 0
e

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [33]:
f = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype='int16')
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
f[1,1,:]

array([7, 8], dtype=int16)

In [35]:
f[0,1,1:]

#Combining these two parts together, f[0,:,1:] selects the first layer, then selects all rows, and from each row, it selects columns from the second column onwards. The result is the subarray:


array([4], dtype=int16)

In [36]:
f[0,:,1:] = 10
f

array([[[ 1, 10],
        [ 3, 10]],

       [[ 5,  6],
        [ 7,  8]]], dtype=int16)

In [37]:
f[:,1,:] = [[9,9],[8,8]]
f

array([[[ 1, 10],
        [ 9,  9]],

       [[ 5,  6],
        [ 8,  8]]], dtype=int16)

In [38]:
#all xeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [41]:
np.ones((4,2,2),dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [42]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [43]:
np.full_like(c,4)

array([[[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [44]:

g = np.random.rand(4,2)
g

array([[0.22060123, 0.85958384],
       [0.27857786, 0.68557136],
       [0.53738959, 0.93969494],
       [0.25455632, 0.98908235]])

In [45]:
h = 2 * g
h

array([[0.44120245, 1.71916768],
       [0.55715573, 1.37114272],
       [1.07477918, 1.87938989],
       [0.50911263, 1.97816471]])

In [46]:
i = np.random.rand(4,2,3)
i

array([[[0.48787827, 0.58319723, 0.93269936],
        [0.05035337, 0.5296315 , 0.63056998]],

       [[0.28264037, 0.91793018, 0.82116245],
        [0.75627931, 0.26836598, 0.23028739]],

       [[0.98764936, 0.19659646, 0.27661151],
        [0.6822507 , 0.96882632, 0.90448094]],

       [[0.44835203, 0.00509159, 0.73242658],
        [0.19910928, 0.97765201, 0.27454027]]])

In [47]:
np.random.randn(10,10)

array([[-4.26253386e-01, -5.58444053e-01, -1.27350329e+00,
        -1.78513948e+00, -1.01678286e+00,  5.78970708e-01,
        -3.69975529e-01,  4.65294502e-01,  1.12448739e+00,
         1.46904351e+00],
       [-1.83385231e+00,  2.81629627e-02, -4.80609128e-01,
         1.85184354e-01,  1.18790684e+00, -3.58537882e-01,
         3.83056700e-01, -1.47606283e+00, -1.10027185e+00,
        -2.71286453e-01],
       [ 2.28330846e-02, -5.82952692e-01,  9.46572550e-01,
         9.37527863e-01,  2.10191788e+00,  1.83292575e+00,
         8.15550995e-01, -4.75167658e-01,  1.52852957e+00,
         5.91239018e-01],
       [-4.89159081e-01, -1.04682509e+00,  1.39817306e+00,
         2.67740450e+00,  4.62849685e-02,  1.04034855e-01,
         2.22989241e-01, -1.63124740e-02,  9.96853029e-01,
        -4.28976978e-01],
       [ 1.73392292e+00, -1.48852883e-01,  5.17374153e-01,
        -5.66743520e-01,  1.18535077e+00, -8.51150080e-01,
        -1.82798089e+00,  9.67310142e-01,  7.36895640e-01,
        -4.

In [48]:
np.random.random_sample(a.shape)

array([0.15178248, 0.06406096, 0.71300372])

In [49]:
np.random.randint(7,size=(3,3))

array([[3, 1, 6],
       [0, 5, 6],
       [5, 3, 0]])

In [50]:
np.random.randint(4,7,size=(3,3))

array([[5, 5, 4],
       [5, 4, 4],
       [6, 6, 6]])

In [51]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [52]:
r1 = np.repeat(a,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int16)

In [53]:
r1 = np.repeat(c,3,axis=0)
r1

array([[[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]],

       [[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]],

       [[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]],

       [[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]],

       [[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]],

       [[1. , 2. , 3. ],
        [3.1, 2.3, 1.2]]])

In [54]:
k = np.ones((5,5))
k[1:4,1:4] = 0
k[2,2] = 9
k

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
a = np.array([1,2,3],dtype='int16')
b = a.copy()
b[0] = 10
b,a

(array([10,  2,  3], dtype=int16), array([1, 2, 3], dtype=int16))

#######MATHEMATICS!!!!!!!!


In [56]:
a = np.array([1,2,3,4,5,6,7,8],dtype='int8')

In [57]:
a+2,a-2,a*2,a/2,a%2,a//2

(array([ 3,  4,  5,  6,  7,  8,  9, 10], dtype=int8),
 array([-1,  0,  1,  2,  3,  4,  5,  6], dtype=int8),
 array([ 2,  4,  6,  8, 10, 12, 14, 16], dtype=int8),
 array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ]),
 array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int8),
 array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int8))

In [58]:
a += 2
a

array([ 3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [59]:
b = np.array([1,2,3,4,5,6,7,8])
a+b

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
a ** 2

array([  9,  16,  25,  36,  49,  64,  81, 100], dtype=int8)

In [61]:
np.sin(a)

array([ 0.1411, -0.757 , -0.959 , -0.2793,  0.657 ,  0.9893,  0.412 ,
       -0.544 ], dtype=float16)

In [62]:
np.cos(a)

array([-0.99  , -0.654 ,  0.2837,  0.96  ,  0.754 , -0.1455, -0.911 ,
       -0.839 ], dtype=float16)

######linear algebra!!!!!

In [63]:
a = np.full((2,3),2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [64]:
b = np.full((3,2),3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [65]:
np.matmul(a,b)

array([[18, 18],
       [18, 18]])

In [66]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [67]:
d = np.linalg.inv(c)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
eigenvalues, eigenvectors = np.linalg.eig(c)

eigenvalues, eigenvectors

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

###Statistics!!!

In [69]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.min(stats)

1

In [71]:
np.max(stats)

6

In [72]:
np.min(stats,axis=1)

array([1, 4])

In [73]:
np.max(stats,axis=1)

array([3, 6])

In [74]:
np.sum(stats)

21

In [75]:
np.sum(stats,axis=1)

array([ 6, 15])

In [76]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c = a.copy()
b = a.reshape((1,14))
a,b

(array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]))

In [77]:
np.vstack((a,c))

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [82]:
a,c

(array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]))

In [85]:
c = np.random.rand(2,7)

In [86]:
np.hstack((a,c))

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  0.48166446,  0.74607282,  0.38969943,
         0.9432818 ,  0.0693006 ,  0.16671586,  0.27004886],
       [ 8.        ,  9.        , 10.        , 11.        , 12.        ,
        13.        , 14.        ,  0.77968102,  0.60701333,  0.99373329,
         0.69824803,  0.5107965 ,  0.48076265,  0.29829559]])

In [92]:
file_data = np.genfromtxt('example.txt',delimiter=',',dtype='int8')
file_data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int8)

In [95]:
file_data = file_data.astype('int16')
file_data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int16)

In [98]:
file_data > 8

array([[False, False, False, False, False, False, False, False,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
         True]])

In [99]:
file_data[file_data > 8]

array([ 9, 10,  9, 10], dtype=int16)

In [103]:
file_data[[0,1]]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int16)

In [106]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,1,2,3,4,7,8]]

array([1, 2, 3, 4, 5, 8, 9])

In [120]:
np.any(file_data > 9,axis=0)

array([False, False, False, False, False, False, False, False, False,
        True])

In [123]:
file_data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int16)

In [122]:
np.all(file_data > 9,axis=1)

array([False, False])

In [125]:
((file_data > 2) & (file_data < 6))

array([[False, False,  True,  True,  True, False, False, False, False,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False]])

In [126]:
file_data[((file_data > 2) & (file_data < 6))]

array([3, 4, 5, 3, 4, 5], dtype=int16)

In [128]:
a = np.ones(2)
np.all(a > 0)

True

In [129]:
file_data[~((file_data > 2) & (file_data < 6))]

array([ 1,  2,  6,  7,  8,  9, 10,  1,  2,  6,  7,  8,  9, 10],
      dtype=int16)

In [ ]:
a = np.array()

In [132]:
a = np.arange(1,31)
a = a.reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [133]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [134]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [137]:
a[[]]

array([], shape=(0, 0), dtype=int32)